version: '3'
services:
  chatgpt-telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: chatgpt
      POSTGRES_USER: chatgpt
      POSTGRES_PASSWORD: chatgpt
    volumes:
      - chatgpt-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  chatgpt-db: